name: Build Windows Desktop App

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2019

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build Executable with PyInstaller
      run: |
        pyinstaller --noconsole --onefile ^
          --add-data "font.ttf;." ^
          --add-data "bg1.mp3;." ^
          --add-data "bg2.mp3;." ^
          --name="FactVideoGenerator" app.py

    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Windows-Desktop-App
        path: dist/FactVideoGenerator.exe
